version: "3"

services:
  aapanel:
    # platform: linux/x86_64
    build: 
      context: ./bin/aapanel
    container_name: "aapanel-webserver"
    ports:
      - "${AAPANEL_PORT}:7800"
      - "${WEBSERVER_HOST_PORT}:80"
      - "${WEBSERVER_SECURE_HOST_PORT}:443"
      - "${PHPMYADMIN_PORT}:888"
    volumes: 
      - ${WEBSITE_DATA}1:/www/wwwroot
      - ${MYSQL_DATA}1:/www/server/data
      - ${WEBSITE_LOG}1:/www/wwwlogs
